services:
  redis:
    image: redis:6.2.3
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis:/data
    networks:
      - bnet

  mongodb:
    image: mongo:8.0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb80:/data/db
    networks:
      - bnet

networks:
  bnet:
    driver: bridge
